### ISSUE TITLE
The script crashes when some of the nodes are unavailable

### ISSUE THREAD

**Issue by Entityless** [Entityless/mpi4py_cluster_monitor#1]
Traceback (most recent call last):
  File "doge.py", line 208, in <module>
    lns = ret_dic[hn]
KeyError: 'hpc8.cse.cuhk.edu.hk'

**Comment by Entityless** [comment]
Traceback (most recent call last):
  File "doge.py", line 267, in <module>
    node_status[hn]['mu'] = str(mem_actually_used) +" MB"
KeyError: 'hpc4.cse.cuhk.edu.hk'
